# Generated by Django 4.2.6 on 2023-11-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='longitude',
            new_name='lon',
        ),
    ]
